// ---------- Web Audio: car-like synthesized sounds ----------
let ac=null,idleNodes=[];function audio(){if(!ac)ac=new(window.AudioContext||window.webkitAudioContext)();if(ac.state==='suspended')ac.resume();return ac}
function gainNode(a,vol=.1){let g=a.createGain();g.gain.value=vol*volumeGain()/.11;g.connect(a.destination);return g}
function osc(a,type,f,g){let o=a.createOscillator();o.type=type;o.frequency.value=f;o.connect(g);return o}
function burst(freq=140,dur=.12,type='square',vol=.07){if(!volumeGain())return;try{let a=audio(),g=gainNode(a,vol);let o=osc(a,type,freq,g);g.gain.setValueAtTime(vol*volumeGain()/.11,a.currentTime);g.gain.exponentialRampToValueAtTime(.0001,a.currentTime+dur);o.start();o.stop(a.currentTime+dur)}catch{}}
function shiftSound(){burst(85,.055,'square',.07);setTimeout(()=>burst(180,.045,'triangle',.05),45)}
function countdownBeep(high=false){burst(high?900:620,.11,'square',.06)}
function revSound(id=s.selectedSound,dur=1.15){if(!volumeGain())return;let sp=SOUNDS.find(x=>x.id===id)||SOUNDS[0];try{let a=audio(),master=gainNode(a,.09),f=a.createBiquadFilter();f.type='lowpass';f.frequency.value=id==='ev'?2800:1200;f.connect(master);let o1=a.createOscillator(),o2=a.createOscillator(),lfo=a.createOscillator(),lg=a.createGain();o1.type=sp.wave;o2.type=id==='ev'?'sine':'triangle';o1.connect(f);o2.connect(f);lfo.connect(lg);lg.connect(o1.frequency);lfo.frequency.value=id==='v8'?22:id==='v10'?31:id==='v12'?36:id==='turbo'?28:6;lg.gain.value=id==='ev'?4:10;let t=a.currentTime,b=sp.base;o1.frequency.setValueAtTime(b,t);o1.frequency.exponentialRampToValueAtTime(b*5.8,t+dur*.72);o1.frequency.exponentialRampToValueAtTime(b*2.3,t+dur);o2.frequency.setValueAtTime(b*sp.harm,t);o2.frequency.exponentialRampToValueAtTime(b*sp.harm*5.1,t+dur*.72);o2.frequency.exponentialRampToValueAtTime(b*sp.harm*2.1,t+dur);master.gain.setValueAtTime(.001,t);master.gain.linearRampToValueAtTime(.11*volumeGain()/.11,t+.08);master.gain.exponentialRampToValueAtTime(.0001,t+dur);o1.start(t);o2.start(t);lfo.start(t);[o1,o2,lfo].forEach(o=>o.stop(t+dur+.03));if(id==='turbo'){let wh=a.createOscillator(),wg=gainNode(a,.035);wh.type='sine';wh.frequency.setValueAtTime(800,t+.15);wh.frequency.exponentialRampToValueAtTime(2500,t+dur*.8);wg.gain.setValueAtTime(.001,t);wg.gain.linearRampToValueAtTime(.045*volumeGain()/.11,t+.3);wg.gain.exponentialRampToValueAtTime(.0001,t+dur);wh.connect(wg);wh.start(t);wh.stop(t+dur)}}catch{}}
function ignitionSound(){if(!volumeGain())return;try{audio();for(let i=0;i<5;i++)setTimeout(()=>burst(70+i*4,.12,'sawtooth',.055),i*115);setTimeout(()=>revSound(s.selectedSound,1.35),620)}catch{}}
function tireSqueal(){if(!volumeGain())return;try{let a=audio(),g=gainNode(a,.045),o=a.createOscillator();o.type='sawtooth';o.frequency.setValueAtTime(720,a.currentTime);o.frequency.linearRampToValueAtTime(420,a.currentTime+.5);o.connect(g);g.gain.setValueAtTime(.04*volumeGain()/.11,a.currentTime);g.gain.exponentialRampToValueAtTime(.0001,a.currentTime+.55);o.start();o.stop(a.currentTime+.56)}catch{}}
function startIdle(){stopIdle();if(!volumeGain())return;try{let a=audio(),sp=sound(),g=a.createGain();g.gain.value=.018*volumeGain()/.11;g.connect(a.destination);let o1=a.createOscillator(),o2=a.createOscillator(),l=a.createOscillator(),lg=a.createGain();o1.type=sp.wave;o2.type='triangle';o1.frequency.value=sp.base*1.45;o2.frequency.value=sp.base*sp.harm*1.2;l.frequency.value=sp.id==='ev'?4:20;lg.gain.value=sp.id==='ev'?2:7;l.connect(lg);lg.connect(o1.frequency);o1.connect(g);o2.connect(g);o1.start();o2.start();l.start();idleNodes=[o1,o2,l,g]}catch{}}
function stopIdle(){idleNodes.forEach(n=>{try{n.stop?.()}catch{}try{n.disconnect?.()}catch{}});idleNodes=[]}
function victorySound(){revSound(s.selectedSound,1.5);setTimeout(()=>{[523,659,784,1047].forEach((f,i)=>setTimeout(()=>burst(f,.25,'sine',.05),i*120))},850)}
function ensureDaily(){if(!s.daily||s.daily.date!==dayKey()){s.daily={date:dayKey(),mode:'normal',customTarget:100,rewardTickets:1,points:0,rewardClaimed:false};save()}}
function checkDailyReward(){if(!s.daily.rewardClaimed&&s.daily.points>=target()){s.daily.rewardClaimed=true;let n=Math.max(1,Math.min(3,+s.daily.rewardTickets||1));s.raceTickets+=n;save();return n}return 0}
function checkSoundUnlocks(){for(let x of SOUNDS){if(unlockedSound(x)&&!s.seenSoundUnlocks.includes(x.id)){s.seenSoundUnlocks.push(x.id);save();return {name:x.name,desc:x.desc}}}return null}
function award(points){ensureDaily();s.points+=points;s.totalPoints+=points;s.daily.points+=points;let ticket=checkDailyReward(),newSound=checkSoundUnlocks();save();return {ticket,newSound}}
const views={home,engine,mission,timer,cars,parts,materials,sounds,race,transfer,parent};
function render(){ensureDaily();app.innerHTML=(views[u.screen]||home)();bind()}
function go(x){if(u.run){clearInterval(ti);u.run=false;stopIdle()}if(u.race){clearInterval(ri);u.race=false;stopIdle()}shiftSound();u.screen=x;if(x==='engine')u.key=false;if(x==='mission')u.sel=s.materials.find(m=>!m.done)?.id||null;render()}
function toast(x){u.toast=x;render();setTimeout(()=>{if(u.toast===x){u.toast='';render()}},1600)}
function bind(){document.querySelectorAll('[data-go]').forEach(e=>e.onclick=()=>go(e.dataset.go));document.querySelectorAll('[data-car]').forEach(e=>e.onclick=()=>{s.selectedCarId=+e.dataset.car;save();revSound();render()});document.querySelectorAll('[data-mat]').forEach(e=>e.onclick=()=>{u.sel=+e.dataset.mat;shiftSound();render()});document.querySelectorAll('[data-time]').forEach(e=>e.onclick=()=>{u.min=+e.dataset.time;shiftSound();render()});document.querySelectorAll('[data-part]').forEach(e=>e.onclick=()=>unlock(+e.dataset.part));document.querySelectorAll('[data-done]').forEach(e=>e.onclick=()=>done(+e.dataset.done));document.querySelectorAll('[data-del]').forEach(e=>e.onclick=()=>{s.materials=s.materials.filter(m=>m.id!==+e.dataset.del);save();render()});document.querySelectorAll('[data-preview]').forEach(e=>e.onclick=()=>revSound(e.dataset.preview,1.35));document.querySelectorAll('[data-sound]').forEach(e=>e.onclick=()=>{s.selectedSound=e.dataset.sound;save();revSound();render()});document.querySelectorAll('[data-vol]').forEach(e=>e.onclick=()=>{s.soundVolume=e.dataset.vol;save();if(s.soundVolume!=='off')burst(420,.08,'sine',.05);render()});document.querySelectorAll('[data-mode]').forEach(e=>e.onclick=()=>{s.daily.mode=e.dataset.mode;save();render()});document.querySelectorAll('[data-bonus-ticket]').forEach(e=>e.onclick=()=>{s.raceTickets+=+e.dataset.bonusTicket;save();revSound();toast(`ボーナスレース券 +${e.dataset.bonusTicket}！`)});document.querySelectorAll('[data-bonus-points]').forEach(e=>e.onclick=()=>{let n=+e.dataset.bonusPoints,r=award(n);revSound();toast(`ボーナス +${n}pt${r.ticket?`・レース券+${r.ticket}`:''}`);if(r.newSound)setTimeout(()=>{u.overlay={type:'sound',...r.newSound};render()},700)});document.querySelectorAll('[data-act]').forEach(e=>e.onclick=()=>act[e.dataset.act]?.())}
function key(){if(u.key)return;u.key=true;ignitionSound();render();setTimeout(()=>go('mission'),1700)}
function start(){u.left=u.min*60;u.run=true;u.msg='エンジン全開！行くぞ！';ignitionSound();setTimeout(startIdle,900);tick();render()}
function tick(){clearInterval(ti);ti=setInterval(()=>{u.left--;if(u.left===Math.floor(u.min*30)){u.msg='いいペースだ！このまま行け！';revSound(s.selectedSound,.65)}if(u.left===300){u.msg='残り5分！シフトダウン！';shiftSound()}if(u.left<=0){clearInterval(ti);u.run=false;stopIdle();completeTimer()}render()},1000)}
function pause(){u.run=false;clearInterval(ti);stopIdle();shiftSound();render()}
function resume(){u.run=true;u.msg='お前ならできる！';revSound(s.selectedSound,.65);startIdle();tick();render()}
function reset(){u.run=false;u.left=0;clearInterval(ti);stopIdle();render()}
function completeTimer(){let p=PT[u.min]||30,t=dayKey(),y=new Date();y.setDate(y.getDate()-1);let st=s.streak,b=0;if(s.lastStudyDate===dayKey(y)){st++;if(st%3===0)b=30}else if(s.lastStudyDate!==t)st=1;s.streak=st;s.lastStudyDate=t;s.sessions.push({date:t,minutes:u.min,pts:p+b});let r=award(p+b);victorySound();u.overlay={type:'done',pt:p+b,ticket:r.ticket,newSound:r.newSound};render()}
function unlock(id){let p=P.find(x=>x.id===id);if(s.unlockedParts.includes(id))return;if(s.points<p.cost)return toast('ポイントが足りません');s.points-=p.cost;s.unlockedParts.push(id);save();shiftSound();u.overlay={type:'part',ico:p.ico,name:p.name};render();setTimeout(()=>{if(u.overlay?.type==='part'){u.overlay=null;render()}},1300)}
function done(id){let m=s.materials.find(x=>x.id===id);if(!m||m.done)return;m.done=true;let r=award(25);victorySound();toast(`+25pt！教材完了${r.ticket?`・レース券+${r.ticket}`:''}`);if(r.newSound)setTimeout(()=>{u.overlay={type:'sound',...r.newSound};render()},700)}
function completeSel(){if(u.sel)done(u.sel)}
function unlockParent(){if($('#code')?.value==='1234'){u.parent=true;shiftSound();render()}else toast('コードが違います')}
function unlockParentSettings(){unlockParent()}
function add(){let n=$('#mn')?.value.trim();if(!n)return toast('教材名を入力してください');s.materials.push({id:s.nextMaterialId++,name:n,subject:$('#ms')?.value.trim(),difficulty:+$('#md')?.value,done:false});save();render()}
function saveParent(){if(s.daily.mode==='custom')s.daily.customTarget=Math.max(10,Math.min(500,+($('#customTarget')?.value||100)));s.daily.rewardTickets=Math.max(1,Math.min(3,+($('#rewardTickets')?.value||1)));let t=checkDailyReward();save();revSound();toast(`今日の設定を保存${t?`・レース券+${t}`:''}`)}
function startRace(){if(!canRace())return toast('レース券がありません');if(!permanentRace()){s.raceTickets--;save()}u.p=u.cpu=0;u.result=null;u.count=3;countdownBeep();render();ci=setInterval(()=>{u.count--;if(u.count>0)countdownBeep();if(u.count<=0){clearInterval(ci);u.count=null;countdownBeep(true);tireSqueal();revSound(s.selectedSound,2.2);u.race=true;runRace()}render()},850)}
function runRace(){let boost=Math.min(s.totalPoints/1200,.55)+.15;ri=setInterval(()=>{u.p+=2.7+boost+Math.random()*1.45;u.cpu+=2.45+Math.random()*1.35;if(Math.random()<.08)shiftSound();if(u.p>=100||u.cpu>=100){clearInterval(ri);u.race=false;u.p=Math.min(100,u.p);u.cpu=Math.min(100,u.cpu);u.result=u.p>=100&&u.p>=u.cpu?'win':'lose';stopIdle();u.result==='win'?victorySound():shiftSound()}render()},110)}
function enc(x){return btoa(unescape(encodeURIComponent(x)))}function dec(x){return decodeURIComponent(escape(atob(x)))}function exportD(){let e=$('#out');if(e)e.value=enc(JSON.stringify(s))}async function copy(){let e=$('#out');if(!e?.value)return;try{await navigator.clipboard.writeText(e.value);toast('コピーしました')}catch{e.select();document.execCommand('copy')}}function importD(){try{s={...fresh(),...JSON.parse(dec($('#in').value.trim()))};if(!s.daily||s.daily.date!==dayKey())s.daily=fresh().daily;save();toast('引き継ぎ完了！');setTimeout(()=>go('home'),500)}catch{toast('コードが正しくありません')}}
const act={key,start,pause,resume,reset,completeSel,unlock:unlockParent,unlockParentSettings,add,race:startRace,export:exportD,copy,import:importD,saveParent,close:()=>{u.overlay=null;go('home')},closeOverlay:()=>{u.overlay=null;render()}};
if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
save();render();