function raceV6(){let perm=permanentRace();if(!canRace())return page(`<div class="head">${back()}<h2>🏁 3D DRIVE</h2></div><div class="card result"><div class="big">🔒</div><h3>まだレースできません</h3><p class="muted">全20パーツを集めるか、保護者からボーナスレース券をもらおう！</p></div>`);
 return page(`<div class="head">${back()}<div><div class="eyebrow">NEON CIRCUIT</div><h2>🏎️ 3D DRIVE</h2></div><span class="ticket">${perm?'🏆 FREE':`🎫 ×${s.raceTickets}`}</span></div>
 <div class="raceHud"><span>速度 <b id="raceSpeed">0</b> km/h</span><span>進捗 <b id="raceProgress">0</b>%</span><span id="raceStatus">START GRID</span></div>
 <div class="race3dWrap card"><canvas id="race3d" width="720" height="900"></canvas><div id="raceCountdown" class="raceCountdown3d"></div><div id="raceResult3d" class="raceResult3d"></div></div>
 <div class="steerZone"><div class="steerLabel">ハンドルを左右に回してコースを走ろう</div><div id="steeringWheel" class="steeringWheel"><div class="wheelHub">🏁</div><div class="wheelGrip g1"></div><div class="wheelGrip g2"></div><div class="wheelGrip g3"></div></div><div class="steerHint">← 左へ　　右へ →</div></div>
 <button id="raceStart3d" class="primary big" data-act="race3d">${u.result?'もう一度走る！':'レーススタート！'}</button><p class="tiny" style="text-align:center">道から外れると減速。左右スワイプ・矢印キーでも操作できます。</p>`)}

function initRaceCanvas(){let c=$('#race3d');if(!c)return;raceImg=new Image();raceImg.src='assets/supercar.webp';drawRacePreview()}
function roadCurve(d){return Math.sin(d/420)*.58+Math.sin(d/950)*.28}
function drawRacePreview(){let c=$('#race3d');if(!c)return;drawRaceScene(c.getContext('2d'),c.width,c.height,0,0,0,500)}
function drawRaceScene(ctx,w,h,dist,lane,speed,cpuDist){
 let horizon=h*.32;ctx.clearRect(0,0,w,h);
 let sky=ctx.createLinearGradient(0,0,0,horizon);sky.addColorStop(0,'#04101e');sky.addColorStop(.65,'#126aa0');sky.addColorStop(1,'#f08b3d');ctx.fillStyle=sky;ctx.fillRect(0,0,w,horizon);
 ctx.fillStyle='#07140f';ctx.fillRect(0,horizon,w,h-horizon);
 ctx.fillStyle='#152434';ctx.beginPath();ctx.moveTo(0,horizon);for(let x=0;x<=w;x+=40){let y=horizon-30-Math.sin(x*.025+dist*.002)*45-Math.sin(x*.009)*22;ctx.lineTo(x,y)}ctx.lineTo(w,horizon);ctx.closePath();ctx.fill();
 let segs=64,prev=null;for(let i=0;i<=segs;i++){let z=i/segs,y=horizon+Math.pow(z,1.72)*(h-horizon),half=28+Math.pow(z,1.16)*w*.45,look=dist+(1-z)*1150,center=w/2+roadCurve(look)*w*.23*(1-z*.25)-lane*w*.20*z;let cur={z,y,half,center};if(prev){let alt=((Math.floor((dist/35)+(i)))%2===0);ctx.fillStyle=alt?'#0a351d':'#0d4523';ctx.fillRect(0,prev.y,w,cur.y-prev.y+1);ctx.beginPath();ctx.moveTo(prev.center-prev.half,prev.y);ctx.lineTo(prev.center+prev.half,prev.y);ctx.lineTo(cur.center+cur.half,cur.y);ctx.lineTo(cur.center-cur.half,cur.y);ctx.closePath();ctx.fillStyle=alt?'#292d33':'#25292f';ctx.fill();let curb=Math.max(3,cur.half*.055);ctx.fillStyle=alt?'#f4f4f4':'#d92727';ctx.beginPath();ctx.moveTo(prev.center-prev.half,prev.y);ctx.lineTo(prev.center-prev.half-curb,prev.y);ctx.lineTo(cur.center-cur.half-curb,cur.y);ctx.lineTo(cur.center-cur.half,cur.y);ctx.closePath();ctx.fill();ctx.beginPath();ctx.moveTo(prev.center+prev.half,prev.y);ctx.lineTo(prev.center+prev.half+curb,prev.y);ctx.lineTo(cur.center+cur.half+curb,cur.y);ctx.lineTo(cur.center+cur.half,cur.y);ctx.closePath();ctx.fill();if((i+Math.floor(dist/30))%6<3){for(let k of [-1/3,1/3]){let x1=prev.center+prev.half*k,x2=cur.center+cur.half*k;ctx.strokeStyle='#dce7ee';ctx.lineWidth=Math.max(1,cur.half*.016);ctx.beginPath();ctx.moveTo(x1,prev.y);ctx.lineTo(x2,cur.y);ctx.stroke()}}if(i%8===0&&i>8){let size=4+z*18;for(let side of [-1,1]){let px=center+side*(half+curb+18+z*30);ctx.fillStyle='#eaeaea';ctx.fillRect(px-size*.18,y-size,size*.36,size);ctx.fillStyle='#ff3b2f';ctx.fillRect(px-size*.18,y-size,size*.36,size*.28)}}}prev=cur}
 let rel=cpuDist-dist;if(rel>20&&rel<950){let z=1-rel/950,z2=Math.max(.05,z),py=horizon+Math.pow(z2,1.72)*(h-horizon),half=28+Math.pow(z2,1.16)*w*.45,center=w/2+roadCurve(dist+rel)*w*.23*(1-z2*.25)-lane*w*.20*z2;let cw=36+z2*120,ch=cw*.46;if(raceImg?.complete){ctx.save();ctx.filter='hue-rotate(320deg) saturate(1.8)';ctx.drawImage(raceImg,center-cw/2,py-ch,cw,ch);ctx.restore()}else{ctx.fillStyle='#d22';ctx.fillRect(center-cw/2,py-ch,cw,ch)}}
 if(speed>45){ctx.strokeStyle='rgba(255,255,255,.22)';ctx.lineWidth=2;for(let i=0;i<12;i++){let x=(i*83+dist*4)%w;ctx.beginPath();ctx.moveTo(x,h*.58);ctx.lineTo(x+(x-w/2)*.08,h*.82);ctx.stroke()}}
 let carW=w*.34,carH=carW*.46,carX=w/2-carW/2+race3d.steer*w*.045;if(raceImg?.complete){ctx.save();ctx.filter=car().f;ctx.translate(carX+carW/2,h-carH*.62);ctx.rotate(race3d.steer*.06);ctx.drawImage(raceImg,-carW/2,-carH,carW,carH);ctx.restore()}else{ctx.fillStyle='#ff7600';ctx.fillRect(carX,h-carH,carW,carH)}
 if(Math.abs(lane)>1.04){ctx.fillStyle='rgba(255,91,39,.16)';ctx.fillRect(0,0,w,h)}
}
function startRace3D(){if(!permanentRace()&&s.raceTickets<=0)return toast('レース券がありません');if(!permanentRace()){s.raceTickets--;save()}u.result=null;race3d={active:false,playerDist:0,cpuDist:0,speed:0,lane:0,steer:0,last:0,finish:2500,offroad:false,result:null,lastCue:0};let btn=$('#raceStart3d');if(btn)btn.style.display='none';let cd=$('#raceCountdown');let n=3;if(cd)cd.textContent=n;countdownBeep();clearInterval(raceCountdownTimer);raceCountdownTimer=setInterval(()=>{n--;if(n>0){if(cd)cd.textContent=n;countdownBeep()}else{clearInterval(raceCountdownTimer);if(cd)cd.textContent='GO!';countdownBeep(true);tireSqueal();pleasantCue(3);setTimeout(()=>{if(cd)cd.textContent=''},550);race3d.active=true;race3d.last=performance.now();raceRAF=requestAnimationFrame(raceLoop)}},700)}
function raceLoop(ts){if(!race3d.active)return;let dt=Math.min(.033,(ts-race3d.last)/1000||.016);race3d.last=ts;let curve=roadCurve(race3d.playerDist+180);race3d.lane+=race3d.steer*dt*1.7+curve*dt*.22;race3d.lane=Math.max(-1.65,Math.min(1.65,race3d.lane));race3d.offroad=Math.abs(race3d.lane)>1.05;let targetSpeed=race3d.offroad?31:57;race3d.speed+=(targetSpeed-race3d.speed)*dt*2.1;race3d.playerDist+=race3d.speed*dt;let cpuBase=52.5+Math.min(3,s.totalPoints/700);race3d.cpuDist+=cpuBase*dt*(.97+Math.sin(ts/1200)*.025);if(ts-race3d.lastCue>6000){race3d.lastCue=ts;pleasantCue(2);setTimeout(shiftSound,260)}let c=$('#race3d');if(c)drawRaceScene(c.getContext('2d'),c.width,c.height,race3d.playerDist,race3d.lane,race3d.speed,race3d.cpuDist);let sp=$('#raceSpeed'),pr=$('#raceProgress'),st=$('#raceStatus');if(sp)sp.textContent=Math.round(race3d.speed*4.4);if(pr)pr.textContent=Math.min(100,Math.round(race3d.playerDist/race3d.finish*100));if(st)st.textContent=race3d.offroad?'⚠️ OFF ROAD':'🏁 ON TRACK';if(race3d.playerDist>=race3d.finish||race3d.cpuDist>=race3d.finish){finishRace3D(race3d.playerDist>=race3d.finish&&race3d.playerDist>=race3d.cpuDist);return}raceRAF=requestAnimationFrame(raceLoop)}
function finishRace3D(win){race3d.active=false;cancelAnimationFrame(raceRAF);u.result=win?'win':'lose';let box=$('#raceResult3d');if(box)box.innerHTML=`<div class="raceResultCard"><div>${win?'🏆':'🏁'}</div><b>${win?'YOU WIN!':'2nd PLACE'}</b><small>${win?'ナイスドライブ！':'もう一度コースへ！'}</small></div>`;if(win)victorySound();else pleasantCue(1);let btn=$('#raceStart3d');if(btn){btn.style.display='block';btn.textContent='もう一度走る！'}}
function bindSteering(){let w=$('#steeringWheel');if(!w)return;let down=false;const set=(clientX)=>{let r=w.getBoundingClientRect(),v=(clientX-(r.left+r.width/2))/(r.width*.46);race3d.steer=Math.max(-1,Math.min(1,v));w.style.transform=`rotate(${race3d.steer*72}deg)`};w.onpointerdown=e=>{down=true;w.setPointerCapture?.(e.pointerId);set(e.clientX)};w.onpointermove=e=>{if(down)set(e.clientX)};w.onpointerup=w.onpointercancel=()=>{down=false;race3d.steer=0;w.style.transform='rotate(0deg)'};document.onkeydown=e=>{if(u.screen!=='race')return;if(e.key==='ArrowLeft')race3d.steer=-1;if(e.key==='ArrowRight')race3d.steer=1};document.onkeyup=e=>{if(['ArrowLeft','ArrowRight'].includes(e.key))race3d.steer=0};let wrap=$('.race3dWrap');if(wrap){let sx=null;wrap.ontouchstart=e=>sx=e.touches[0].clientX;wrap.ontouchmove=e=>{if(sx==null)return;let dx=e.touches[0].clientX-sx;race3d.steer=Math.max(-1,Math.min(1,dx/90));w.style.transform=`rotate(${race3d.steer*72}deg)`};wrap.ontouchend=()=>{sx=null;race3d.steer=0;w.style.transform='rotate(0deg)'}}}
function cleanupV6(){clearInterval(breakTimer);clearInterval(returnTimer);clearInterval(raceCountdownTimer);cancelAnimationFrame(raceRAF);race3d.active=false;document.onkeydown=null;document.onkeyup=null}
