// v7: minute-based focus cues. No percentage-based sounds.
if(!s.timerNotice)s.timerNotice='voice';
function speechVolume(){return {off:0,small:.35,medium:.65,large:.9}[s.soundVolume]??.65}
function speakRemaining(mins){if(!mins||s.timerNotice!=='voice'||!('speechSynthesis' in window))return;try{speechSynthesis.cancel();let u2=new SpeechSynthesisUtterance(`残り${mins}分`);u2.lang='ja-JP';u2.rate=1.03;u2.pitch=1.03;u2.volume=speechVolume();speechSynthesis.speak(u2)}catch{}}
function minuteCue(mins){if(s.timerNotice==='quiet')return;if(s.timerNotice==='tone'){pleasantCue(mins<=5?3:1);return}pleasantCue(mins<=5?3:1);setTimeout(()=>speakRemaining(mins),180)}
function timerV7(){if(u.timerMode==='break')return timerV6();let total=u.min*60,p=(u.run||u.left>0)?(total-u.left)/total:0,m=Math.floor(u.left/60),sec=u.left%60;return page(`<div class="timerhead">${back('home')}<div class="muted">📚 ${esc(s.materials.find(x=>x.id===u.sel)?.name||'フリー学習')}</div></div><div class="modeTabs"><button class="on" data-timer-mode="study">🏁 集中</button><button data-timer-mode="break">🛠 休憩</button></div>${u.msg?`<div class="card ray">🏎️ 「${esc(u.msg)}」</div>`:''}<div class="card focusCard minuteCard"><div><b>MINUTE CUE</b><div class="muted">進捗%ではなく、残り時間を1分ごとに知らせます。</div></div><div class="minuteBtns"><button class="chip ${s.timerNotice==='voice'?'on':''}" data-notice="voice">🗣 残り○分</button><button class="chip ${s.timerNotice==='tone'?'on':''}" data-notice="tone">🔈 音だけ</button><button class="chip ${s.timerNotice==='quiet'?'on':''}" data-notice="quiet">🔇 静か</button></div></div><div class="gauge" style="--p:${p}"><div class="face"><div><div class="time">${String(m).padStart(2,'0')}:${String(sec).padStart(2,'0')}</div><div class="remaining">REMAINING</div></div></div></div>${!u.run&&u.left===0?`<div class="times">${OPT.map(x=>`<button data-time="${x}" class="${u.min===x?'on':''}">${x}分<small>+${PT[x]}pt</small></button>`).join('')}</div>`:''}<div class="controls">${!u.run&&u.left===0?'<button class="primary big" data-act="start">▶ スタート！</button>':''}${u.run?'<button class="secondary" data-act="pause">⏸ 一時停止</button>':''}${!u.run&&u.left>0?'<button class="primary" data-act="resume">▶ 再開</button><button class="secondary" data-act="reset">リセット</button>':''}</div>${u.sel&&!s.materials.find(x=>x.id===u.sel)?.done&&u.left>0?'<button class="success big" data-act="completeSel" style="width:100%;margin-top:12px">🎉 教材おわった！ +25pt</button>':''}${!u.run&&u.left===0?'<button class="secondary big" data-timer-mode="break" style="width:100%;margin-top:12px">🛠 先に休憩タイマーを使う</button>':''}`)}
function startStudyV7(){u.timerMode='study';s.lastStudyMinutes=u.min;u.left=u.min*60;u.run=true;u.msg='スタート！コースへ出よう。';ignitionSound();save();tickStudyV7();render()}
function tickStudyV7(){clearInterval(ti);ti=setInterval(()=>{u.left--;if(u.left>0&&u.left%60===0){let rem=u.left/60;u.msg=`残り${rem}分！`;minuteCue(rem)}if(u.left===30){u.msg='残り30秒！ゴールはすぐそこ！';if(s.timerNotice!=='quiet')pleasantCue(3)}if(u.left<=0){clearInterval(ti);u.run=false;completeTimer()}render()},1000)}
function resumeStudyV7(){u.run=true;u.msg='再スタート！';if(s.timerNotice!=='quiet')pleasantCue(1);tickStudyV7();render()}
function resetStudyV7(){u.run=false;u.left=0;clearInterval(ti);try{speechSynthesis.cancel()}catch{}render()}
function returnStudyV7(){u.overlay={type:'returnStudy',count:3};render();let c=3;countdownBeep();clearInterval(returnTimer);returnTimer=setInterval(()=>{c--;if(c>0){u.overlay={type:'returnStudy',count:c};countdownBeep();render()}else{clearInterval(returnTimer);countdownBeep(true);u.overlay=null;u.timerMode='study';u.min=s.lastStudyMinutes||20;startStudyV7()}},800)}
const bindBeforeTimerV7=bind;bind=function(){bindBeforeTimerV7();document.querySelectorAll('[data-notice]').forEach(e=>e.onclick=()=>{s.timerNotice=e.dataset.notice;save();if(s.timerNotice==='voice')speakRemaining(5);else if(s.timerNotice==='tone')pleasantCue(2);render()})};
views.timer=timerV7;act.start=startStudyV7;act.resume=resumeStudyV7;act.reset=resetStudyV7;act.returnStudy=returnStudyV7;
